export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const ADD_MARKETING_SIGNUP_SUCCESS = 'ADD_MARKETING_SIGNUP_SUCCESS';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const OAUTH2_GRANT_SUCCESS = 'OAUTH2_GRANT_SUCCESS';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
