export const LOAD_LAB_REPOSITORIES_SUCCESS = 'LOAD_LAB_REPOSITORIES_SUCCESS';
export const CREATE_LAB_REPOSITORY_SUCCESS = 'CREATE_LAB_REPOSITORY_SUCCESS';
export const UPDATE_LAB_REPOSITORY_SUCCESS = 'UPDATE_LAB_REPOSITORY_SUCCESS';
export const DELETE_LAB_REPOSITORY_SUCCESS = 'DELETE_LAB_REPOSITORY_SUCCESS';
