export const LOAD_REPOSITORY_TYPES_SUCCESS = 'LOAD_REPOSITORY_TYPES_SUCCESS';
export const CREATE_REPOSITORY_TYPE_SUCCESS = 'CREATE_REPOSITORY_TYPE_SUCCESS';
export const UPDATE_REPOSITORY_TYPE_SUCCESS = 'UPDATE_REPOSITORY_TYPE_SUCCESS';
export const DELETE_REPOSITORY_TYPE_SUCCESS = 'DELETE_REPOSITORY_TYPE_SUCCESS';

export const LOAD_ALL_CUSTOM_SLOT_TYPES_SUCCESS = 'LOAD_ALL_CUSTOM_SLOT_TYPES_SUCCESS';
export const LOAD_CUSTOM_SLOT_TYPES_SUCCESS = 'LOAD_CUSTOM_SLOT_TYPES_SUCCESS';
export const CREATE_CUSTOM_SLOT_TYPE_SUCCESS = 'CREATE_CUSTOM_SLOT_TYPE_SUCCESS';
export const UPDATE_CUSTOM_SLOT_TYPE_SUCCESS = 'UPDATE_CUSTOM_SLOT_TYPE_SUCCESS';
export const DELETE_CUSTOM_SLOT_TYPE_SUCCESS = 'DELETE_CUSTOM_SLOT_TYPE_SUCCESS';
