module.exports =  {
  REMINDER_QUEUE: 'jobs.reminders',
  EMAIL_QUEUE: 'jobs.emails',
  INVENTORY_QUEUE: 'jobs.inventory',
  PUBCHEM_QUEUE: 'jobs.pubchem',
  PROTOCOL_ACTION_PARSER_QUEUE : 'jobs.action_parser',
  SLACK_QUEUE: 'jobs.slack_messenger',
  AUDIT_LOG_QUEUE: 'jobs.audit_log_queue',
  APPLICATION_QUEUE: 'jobs.application_queue',
  ENTITY_UPDATE_QUEUE: 'jobs.entity_update_queue',
  REPOSITORY_UPDATE_QUEUE: 'jobs.repository_update_queue',
  APPLICATION_TRAINING_QUEUE: 'jobs.application_training_queue',
  APPLICATION_BUILD_QUEUE: 'jobs.build_queue',
  APPLICATION_BUILD_STATUS_QUEUE: 'jobs.build_status_queue',
  AWS_ALEXA_FOR_BUSINESS_QUEUE: 'jobs.alexa_for_business_queue',
}
