export const LOAD_ACTIVITIES_SUCCESS = 'LOAD_ACTIVITIES_SUCCESS';
export const LOAD_ACTIVITY_SUCCESS = 'LOAD_ACTIVITY_SUCCESS';
export const LOAD_LAB_SUCCESS = 'LOAD_LAB_SUCCESS';
export const CREATE_LAB_SUCCESS = 'CREATE_LAB_SUCCESS';
export const UPDATE_LAB_SUCCESS = 'UPDATE_LAB_SUCCESS';
export const DELETE_LAB_SUCCESS = 'DELETE_LAB_SUCCESS';
export const LOAD_LABORATORY_PROFILE_SUCCESS = 'LOAD_LABORATORY_PROFILE_SUCCESS';
export const CREATE_LABORATORY_PROFILE_SUCCESS = 'CREATE_LABORATORY_PROFILE_SUCCESS';
export const UPDATE_LABORATORY_PROFILE_SUCCESS = 'UPDATE_LABORATORY_PROFILE_SUCCESS';
export const DELETE_LABORATORY_PROFILE_SUCCESS = 'DELETE_LABORATORY_PROFILE_SUCCESS';
export const LOAD_SKILL_GROUPS_SUCCESS = 'LOAD_SKILL_GROUPS_SUCCESS';
export const CREATE_SKILL_GROUP_SUCCESS = 'CREATE_SKILL_GROUP_SUCCESS';
export const UPDATE_SKILL_GROUP_SUCCESS = 'UPDATE_SKILL_GROUP_SUCCESS';
export const DELETE_SKILL_GROUP_SUCCESS = 'DELETE_SKILL_GROUP_SUCCESS';
export const LOAD_LAB_APPLICATIONS_SUCCESS = 'LOAD_LAB_APPLICATIONS_SUCCESS';
export const CREATE_LAB_APPLICATION_SUCCESS = 'CREATE_LAB_APPLICATION_SUCCESS';
export const UPDATE_LAB_APPLICATION_SUCCESS = 'UPDATE_LAB_APPLICATION_SUCCESS';
export const DELETE_LAB_APPLICATION_SUCCESS = 'DELETE_LAB_APPLICATION_SUCCESS';
export const SUBMIT_LAB_APPLICATION_SUCCESS = 'SUBMIT_LAB_APPLICATION_SUCCESS';
export const CREATE_LAB_MEMBER_REPOSITORY_SUCCESS = 'CREATE_LAB_MEMBER_REPOSITORY_SUCCESS';
export const UPDATE_LAB_MEMBER_REPOSITORY_SUCCESS = 'UPDATE_LAB_MEMBER_REPOSITORY_SUCCESS';
export const CREATE_LAB_MEMBER_SUCCESS = 'CREATE_LAB_MEMBER_SUCCESS';
export const UPDATE_LAB_MEMBER_SUCCESS = 'UPDATE_LAB_MEMBER_SUCCESS';
export const DELETE_LAB_MEMBER_SUCCESS = 'DELETE_LAB_MEMBER_SUCCESS';
export const LOAD_LAB_INVENTORY_SUCCESS = 'LOAD_LAB_INVENTORY_SUCCESS';
export const LOAD_INTENTS_SUCCESS = 'LOAD_INTENTS_SUCCESS';
export const LOAD_INVENTORY_SUCCESS = 'LOAD_INVENTORY_SUCCESS';
export const UPLOAD_INVENTORY_SUCCESS = 'UPLOAD_INVENTORY_SUCCESS';
export const LOAD_RECIPES_SUCCESS = 'LOAD_RECIPES_SUCCESS';
export const CREATE_RECIPE_SUCCESS = 'CREATE_RECIPE_SUCCESS';
export const UPDATE_RECIPE_SUCCESS = 'UPDATE_RECIPE_SUCCESS';
export const DELETE_RECIPE_SUCCESS = 'DELETE_RECIPE_SUCCESS';
export const LOAD_COMPOUNDS_SUCCESS = 'LOAD_COMPOUNDS_SUCCESS';
export const CREATE_COMPOUND_SUCCESS = 'CREATE_COMPOUND_SUCCESS';
export const UPDATE_COMPOUND_SUCCESS = 'UPDATE_COMPOUND_SUCCESS';
export const DELETE_COMPOUND_SUCCESS = 'DELETE_COMPOUND_SUCCESS';
export const LOAD_ALL_CUSTOM_SLOT_TYPES_SUCCESS = 'LOAD_ALL_CUSTOM_SLOT_TYPES_SUCCESS';
export const LOAD_CUSTOM_SLOTS_SUCCESS = 'LOAD_CUSTOM_SLOTS_SUCCESS';
export const CREATE_CUSTOM_SLOT_SUCCESS = 'CREATE_CUSTOMS_SLOT_SUCCESS';
export const UPDATE_CUSTOM_SLOT_SUCCESS = 'UPDATE_CUSTOM_SLOT_SUCCESS';
export const DELETE_CUSTOM_SLOT_SUCCESS = 'DELETE_CUSTOM_SLOT_SUCCESS';
export const LOAD_ELEMENTS_SUCCESS = 'LOAD_ELEMENTS_SUCCESS';
export const CREATE_ELEMENT_SUCCESS = 'CREATE_ELEMENT_SUCCESS';
export const UPDATE_ELEMENT_SUCCESS = 'UPDATE_ELEMENT_SUCCESS';
export const DELETE_ELEMENT_SUCCESS = 'DELETE_ELEMENT_SUCCESS';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const LOAD_CLIENTS_SUCCESS = 'LOAD_CLIENTS_SUCCESS';
export const CREATE_CLIENT_SUCCESS = 'CREATE_CLIENT_SUCCESS';
export const UPDATE_CLIENT_SUCCESS = 'UPDATE_CLIENT_SUCCESS';
export const DELETE_CLIENT_SUCCESS = 'DELETE_CLIENT_SUCCESS';

//Companies
export const LOAD_ALL_COMPANIES_SUCCESS = 'LOAD_ALL_COMPANIES_SUCCESS';
export const LOAD_COMPANIES_SUCCESS = 'LOAD_COMPANIES_SUCCESS';
export const CREATE_COMPANY_SUCCESS = 'CREATE_COMPANY_SUCCESS';
export const UPDATE_COMPANY_SUCCESS = 'UPDATE_COMPANY_SUCCESS';
export const DELETE_COMPANY_SUCCESS = 'DELETE_COMPANY_SUCCESS';
export const LOAD_COMPANY_ORDERS = 'LOAD_COMPANY_ORDERS';

export const LOAD_LOOKUPS_SUCCESS = 'LOAD_LOOKUPS_SUCCESS';
export const CREATE_LOOKUP_SUCCESS = 'CREATE_LOOKUP_SUCCESS';
export const UPDATE_LOOKUP_SUCCESS = 'UPDATE_LOOKUP_SUCCESS';
export const DELETE_LOOKUP_SUCCESS = 'DELETE_LOOKUP_SUCCESS';
export const LOAD_ENTITIES_SUCCESS = 'LOAD_ENTITIES_SUCCESS';
export const CREATE_ENTITY_SUCCESS = 'CREATE_ENTITY_SUCCESS';
export const UPLOAD_ENTITIES_SUCCESS = 'UPLOAD_ENTITIES_SUCCESS';
export const UPDATE_ENTITY_SUCCESS = 'UPDATE_ENTITIY_SUCCESS';
export const DELETE_ENTITY_SUCCESS = 'DELETE_ENTITY_SUCCESS';
export const LOAD_ENTITY_PROPERTIES_SUCCESS = 'LOAD_ENTITY_PROPERTIES_SUCCESS';
export const CREATE_ENTITY_PROPERTY_SUCCESS = 'CREATE_ENTITY_PROPERTY_SUCCESS';
export const UPDATE_ENTITY_PROPERTY_SUCCESS = 'UPDATE_ENTITY_PROPERTY_SUCCESS';
export const DELETE_ENTITY_PROPERTY_SUCCESS = 'DELETE_ENTITY_PROPERTY_SUCCESS';
export const LOAD_NOTES_SUCCESS = 'LOAD_NOTES_SUCCESS';
export const CREATE_NOTE_SUCCESS = 'CREATE_NOTE_SUCCESS';
export const UPDATE_NOTE_SUCCESS = 'UPDATE_NOTE_SUCCESS';
export const DELETE_NOTE_SUCCESS = 'DELETE_NOTE_SUCCESS';
export const LOAD_PROTOCOLS_SUCCESS = 'LOAD_PROTOCOLS_SUCCESS';
export const CREATE_PROTOCOL_SUCCESS = 'CREATE_PROTOCOL_SUCCESS';
export const UPDATE_PROTOCOL_SUCCESS = 'UPDATE_PROTOCOL_SUCCESS';
export const DELETE_PROTOCOL_SUCCESS = 'DELETE_PROTOCOL_SUCCESS';
export const LOAD_UNITS_SUCCESS = 'LOAD_UNITS_SUCCESS';
export const CREATE_UNIT_SUCCESS = 'CREATE_UNIT_SUCCESS';
export const UPDATE_UNIT_SUCCESS = 'UPDATE_UNIT_SUCCESS';
export const DELETE_UNIT_SUCCESS = 'DELETE_UNIT_SUCCESS';
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const AUTHENTICATE_USER_SUCCESS = 'AUTHENTICATE_USER_SUCCESS';

export const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN';
export const AUTH_DISCARD_TOKEN = 'AUTH_DISCARD_TOKEN';
export const AUTH_SET_USER = 'AUTH_SET_USER';
export const AUTH_UPDATE_USER = 'AUTH_UPDATE_USER';
export const AUTH_UPDATE_USER_PASSWORD = 'AUTH_UPDATE_USER_PASSWORD';
export const AUTH_SET_APPLICATIONS = 'AUTH_SET_APPLICATIONS';
export const AUTH_SET_COMPANIES = 'AUTH_SET_COMPANIES';
export const AUTH_SET_COMPANY = 'AUTH_SET_COMPANY';
export const AUTH_SET_LABS = 'AUTH_SET_LABS';
export const AUTH_SET_LAB = 'AUTH_SET_LAB';
export const AUTH_SET_NOTES_SUCCESS = 'AUTH_SET_NOTES_SUCCESS';
export const AUTH_SET_INVENTORIES = 'AUTH_SET_INVENTORIES';
export const AUTH_SET_SELECTED_COMPANY = 'AUTH_SET_SELECTED_COMPANY';
export const AUTH_SET_SELECTED_APPLICATION = 'AUTH_SET_SELECTED_APPLICATION';
export const AUTH_SET_SELECTED_LAB = 'AUTH_SET_SELECTED_LAB';
export const AUTH_SET_REPOSITORY = 'AUTH_SET_REPOSITORY';
export const AUTH_SET_REPOSITORIES = 'AUTH_SET_REPOSITORIES';
export const FORGOT_PASSWORD_LINK_SENT = 'FORGOT_PASSWORD_LINK_SENT';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';

export const LOAD_COMPANY_REPOSITORY_GROUPS_SUCCESS = 'LOAD_COMPANY_REPOSITORY_GROUPS_SUCCESS';

export const LOAD_COMPANY_USERS_SUCCESS = 'LOAD_COMPANY_USERS_SUCCESS';
export const CREATE_COMPANY_USER_SUCCESS = 'CREATE_COMPANY_USER_SUCCESS';
export const UPDATE_COMPANY_USER_SUCCESS = 'UPDATE_COMPANY_USER_SUCCESS';
export const DELETE_COMPANY_USER_SUCCESS = 'DELETE_COMPANY_USER_SUCCESS';

export const LOAD_INTENT_LOGS_SUCCESS = 'LOAD_INTENT_LOGS_SUCCESS';
export const CREATE_INTENT_SUCCESS = 'CREATE_INTENT_SUCCESS';
export const UPDATE_INTENT_SUCCESS = 'UPDATE_INTENT_SUCCESS';
export const DELETE_INTENT_SUCCESS = 'DELETE_INTENT_SUCCESS';
export const ADD_MARKETING_SIGNUP_SUCCESS = 'ADD_MARKETING_SIGNUP_SUCCESS';
export const LOAD_ALEXA_SKILLS_SUCCESS = 'LOAD_ALEXA_SKILLS_SUCCESS';
export const CREATE_ALEXA_SKILL_SUCCESS = 'CREATE_ALEXA_SKILL_SUCCESS';
export const UPDATE_ALEXA_SKILL_SUCCESS = 'UPDATE_ALEXA_SKILL_SUCCESS';
export const DELETE_ALEXA_SKILL_SUCCESS = 'DELETE_ALEXA_SKILL_SUCCESS';
export const LOAD_ALL_LOOKUP_PROPERTIES_SUCCESS = 'LOAD_ALL_LOOKUP_PROPERTIES_SUCCESS';
export const LOAD_LOOKUP_PROPERTIES_SUCCESS = 'LOAD_LOOKUP_PROPERTIES_SUCCESS';
export const CREATE_LOOKUP_PROPERTY_SUCCESS = 'CREATE_LOOKUP_PROPERTY_SUCCESS';
export const UPDATE_LOOKUP_PROPERTY_SUCCESS = 'UPDATE_LOOKUP_PROPERTY_SUCCESS';
export const DELETE_LOOKUP_PROPERTY_SUCCESS = 'DELETE_LOOKUP_PROPERTY_SUCCESS';
export const LOAD_VIDEOS_SUCCESS = 'LOAD_VIDEOS_SUCCESS';
export const CREATE_VIDEO_SUCCESS = 'CREATE_VIDEO_SUCCESS';
export const UPDATE_VIDEO_SUCCESS = 'UPDATE_VIDEO_SUCCESS';
export const DELETE_VIDEO_SUCCESS = 'DELETE_VIDEO_SUCCESS';
export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';

export const LOAD_DATA_SETS_SUCCESS = 'LOAD_DATA_SETS_SUCCESS';
export const CREATE_DATA_SET_SUCCESS = 'CREATE_DATA_SET_SUCCESS';
export const UPDATE_DATA_SET_SUCCESS = 'UPDATE_DATA_SET_SUCCESS';
export const DELETE_DATA_SET_SUCCESS = 'DELETE_DATA_SET_SUCCESS';

export const LOAD_REPOSITORIES_SUCCESS = 'LOAD_REPOSITORIES_SUCCESS';
export const CREATE_REPOSITORY_SUCCESS = 'CREATE_REPOSITORY_SUCCESS';
export const UPDATE_REPOSITORY_SUCCESS = 'UPDATE_REPOSITORY_SUCCESS';
export const DELETE_REPOSITORY_SUCCESS = 'DELETE_REPOSITORY_SUCCESS';

export const LOAD_MARKETING_DATA_SETS_SUCCESS = 'LOAD_MARKETING_DATA_SETS_SUCCESS';
export const CREATE_MARKETING_DATA_SET_SUCCESS = 'CREATE_MARKETING_DATA_SET_SUCCESS';
export const UPDATE_MARKETING_DATA_SET_SUCCESS = 'UPDATE_MARKETING_DATA_SET_SUCCESS';
export const DELETE_MARKETING_DATA_SET_SUCCESS = 'DELETE_MARKETING_DATA_SET_SUCCESS';
export const LOAD_MARKETING_DATA_SET_ITEMS_SUCCESS = 'LOAD_MARKETING_DATA_SET_ITEMS_SUCCESS';

export const LOAD_MODULES_SUCCESS = 'LOAD_MODULES_SUCCESS';
export const CREATE_MODULE_SUCCESS = 'CREATE_MODULE_SUCCESS';
export const UPDATE_MODULE_SUCCESS = 'UPDATE_MODULE_SUCCESS';
export const DELETE_MODULE_SUCCESS = 'DELETE_MODULE_SUCCESS';

export const LOAD_APPLICATION_BUILDS_SUCCESS = 'LOAD_APPLICATION_BUILDS_SUCCESS';
export const CREATE_APPLICATION_BUILD_SUCCESS = 'CREATE_APPLICATION_BUILD_SUCCESS';

export const LOAD_APPLICATION_ACCESS_CONTROL_LIST = 'LOAD_APPLICATION_ACCESS_CONTROL_LIST';
export const UPDATE_APPLICATION_ACCESS_CONTROL_LIST = 'UPDATE_APPLICATION_ACCESS_CONTROL_LIST';

export const LOAD_APPLICATION_BETA_TESTING_LIST = 'LOAD_APPLICATION_BETA_TESTING_LIST';
export const UPDATE_APPLICATION_BETA_TESTING_LIST = 'UPDATE_APPLICATION_BETA_TESTING_LIST';

export const LOAD_SYSTEM_SUCCESS = 'LOAD_SYSTEM_SUCCESS';
export const SAVE_ATTRIBUTE_SUCCESS = 'SAVE_ATTRIBUTE_SUCCESS';

export const LOAD_COMPANY_APPLICATIONS_SUCCESS = 'LOAD_COMPANY_APPLICATIONS_SUCCESS';
export const CREATE_COMPANY_APPLICATION_SUCCESS = 'CREATE_COMPANY_APPLICATION_SUCCESS';
export const UPDATE_COMPANY_APPLICATION_SUCCESS = 'UPDATE_COMPANY_APPLICATION_SUCCESS';
export const DELETE_COMPANY_APPLICATION_SUCCESS = 'DELETE_COMPANY_APPLICATION_SUCCESS';

export const LOAD_TRAINING_ITEMS_SUCCESS = 'LOAD_TRAINING_ITEMS_SUCCESS';

export const SET_PAGE_STATE = 'SET_PAGE_STATE';
export const NETWORK_ERROR = 'NETWORK_ERROR';

